# Generated by Django 3.0.7 on 2020-06-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('color', models.CharField(choices=[('K', 'Black'), ('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], default='K', max_length=1)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pen')),
            ],
        ),
    ]
