# Generated by Django 3.0.7 on 2020-06-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200618_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='inks',
            field=models.ManyToManyField(to='main_app.Ink'),
        ),
    ]
